### ISSUE TITLE
Help With Fiber

### ISSUE THREAD

**Issue by WillLuce** [Bogdan-Lyashenko/Under-the-hood-ReactJS#19]
I issued the PR for some grammar fixes a few weeks ago. I'd like to do the same for your Fiber branch if you're ok with that. Let me know how I can help.

**Comment by Bogdan-Lyashenko** [comment]
Hey, thanks for your interest. Erm.. can you please check if I didn't miss anything, the last PR was like 2 months ago - 
https://github.com/Bogdan-Lyashenko/Under-the-hood-ReactJS/pulls?q=is%3Apr+is%3Aclosed
Regarding Fiber, it's not ready yet, so branch is empty for now. Currently I work on library to automate flowchart drawing (it takes JS code - returns svg scheme) will use it for Fiber then, because it takes plenty of time to create that diagrams manually. So, when I finish that, we can proceed with Fiber. Thanks.

**Comment by Bogdan-Lyashenko** [comment]
@WillLuce, you can check out https://github.com/Bogdan-Lyashenko/js-code-to-svg-flowchart, it's not ready yet, but already can be used. I just don't think we should manually draw that flow-charts. Thanks.

**Comment by WillLuce** [comment]
Yep I’ll take a look tonight. Thanks for the invite.

**Comment by tsiq-swyx** [comment]
just checking in! a Fiber version of this would really be amazing!

**Comment by Bogdan-Lyashenko** [comment]
@tsiq-swyx, yeah.. need to find some time for that ;) currently busy with another repo. I think I definitely will do it, but probably in slightly different format, to have it smaller and more clear to understand.
